---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipeapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: recipeapi
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: recipeapi
        image: home-cooking-app:dev
        resources: 
          limits:
            memory: 512Mi
            cpu: "1"
        # ports:
        # - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8001
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: DBHOST
          value: $(POSTGRESDB_SERVICE_HOST)
        - name: DBPORT
          value: "5432"
        - name: DBNAME
          value: "homecooking"
        - name: DBUSERNAME
          value: "homecooking"
        - name: DBPASSWORD
          value: "homecooking"                                        
  selector:
    matchLabels:
      app: recipeapi

---

apiVersion: v1
kind: Service
metadata:
  name: recipeapi-service
spec:
  type: LoadBalancer
  ports:
  - port: 8001
  selector:
    app: recipeapi